version: '3.8'
services:
  backend:
    image: alixcja/home-backend:dev-6
    container_name: backend
    ports:
      - "8000:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://backend-postgres:5432/booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak:8888/realms/master
      - QUARKUS_OIDC_CLIENT_ID=exp-home
    depends_on:
      - backend-postgres
      - keycloak
    networks:
      - app-network

  backend-postgres:
    image: postgres:16
    container_name: backend-postgres
    volumes:
      - home_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking
    ports:
      - "5432:5432"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    command: start
    environment:
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-postgres/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - 8888:8080
    restart: always
    depends_on:
      - keycloak-postgres
    networks:
      - app-network

  keycloak-postgres:
    image: postgres:16
    container_name: keycloak-postgres
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    networks:
      - app-network
    ports:
      - "5433:5432"

  minio:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    networks:
      - app-network
    ports:
      - "9000:9000"
      - "9001:9001"


networks:
  app-network:
    driver: bridge

volumes:
  keycloak_postgres_data:
    driver: local
  home_postgres_data:
    driver: local
  minio_data:
    driver: local